/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as LiveBotRouteImport } from './routes/live-bot'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as StrategyStatsRouteImport } from './routes/strategy-stats'
import { Route as TradesRouteImport } from './routes/trades'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveBotRoute = LiveBotRouteImport.update({
  id: '/live-bot',
  path: '/live-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyStatsRoute = StrategyStatsRouteImport.update({
  id: '/strategy-stats',
  path: '/strategy-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/live-bot': typeof LiveBotRoute
  '/research': typeof ResearchRoute
  '/screener': typeof ScreenerRoute
  '/strategy-stats': typeof StrategyStatsRoute
  '/trades': typeof TradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/live-bot': typeof LiveBotRoute
  '/research': typeof ResearchRoute
  '/screener': typeof ScreenerRoute
  '/strategy-stats': typeof StrategyStatsRoute
  '/trades': typeof TradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/live-bot': typeof LiveBotRoute
  '/research': typeof ResearchRoute
  '/screener': typeof ScreenerRoute
  '/strategy-stats': typeof StrategyStatsRoute
  '/trades': typeof TradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtest'
    | '/live-bot'
    | '/research'
    | '/screener'
    | '/strategy-stats'
    | '/trades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/live-bot'
    | '/research'
    | '/screener'
    | '/strategy-stats'
    | '/trades'
  id:
    | '__root__'
    | '/'
    | '/backtest'
    | '/live-bot'
    | '/research'
    | '/screener'
    | '/strategy-stats'
    | '/trades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  LiveBotRoute: typeof LiveBotRoute
  ResearchRoute: typeof ResearchRoute
  ScreenerRoute: typeof ScreenerRoute
  StrategyStatsRoute: typeof StrategyStatsRoute
  TradesRoute: typeof TradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-bot': {
      id: '/live-bot'
      path: '/live-bot'
      fullPath: '/live-bot'
      preLoaderRoute: typeof LiveBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy-stats': {
      id: '/strategy-stats'
      path: '/strategy-stats'
      fullPath: '/strategy-stats'
      preLoaderRoute: typeof StrategyStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  LiveBotRoute: LiveBotRoute,
  ResearchRoute: ResearchRoute,
  ScreenerRoute: ScreenerRoute,
  StrategyStatsRoute: StrategyStatsRoute,
  TradesRoute: TradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
